### ISSUE TITLE
Test the image uploading feature

### ISSUE THREAD

**Issue by trungtt1981** [FeeSimple/data-manager#55]
Do the test and write the report

**Comment by trungtt1981** [comment]
The image-uploader-to-ipfs `images-to-ipfs` on server is running in `development` mode and thus it uses `HTTP`. However, fsmanager.io is running over `HTTPS` and thus when uploading images with fsmanager.io, the below conflict occurs

```
index.js:25 TypeError: Failed to fetch
FloorplanDetailsContainer._this.onImagesUploaded @ index.js:25
index.js:347 Mixed Content: The page at 'https://fsmanager.io/3/floorplan/new' was loaded over HTTPS, but requested an insecure resource 'http://178.128.67.13:4001/multiple'. This request has been blocked; the content must be served over HTTPS.
_callee$ @ index.js:347
index.js:25 TypeError: Failed to fetch
```

To resolve this, we must run the image-uploader-to-ipfs `images-to-ipfs` with `HTTPS`.
For this, the `NODE_ENV` in file `.env` must be set to `production`.
However, when running the image-uploader-to-ipfs `images-to-ipfs` in `production` mode, encounter problem with `greenlock` as follows:

```
[nodemon] starting `node --experimental-modules -r dotenv/config index.mjs`
(node:18455) ExperimentalWarning: The ESM module loader is experimental.
Using ipfs node at http://138.197.194.220:5001
TypeError: greenLock.create is not a function
    at file:///root/images-to-ipfs/index.mjs:44:13
    at ModuleJob.run (internal/loader/ModuleJob.js:97:14)
    at <anonymous>
[nodemon] app crashed - waiting for file changes before starting...

```

**Notice**
Please do not use port `9001` as it is being used by `nodeos`.
Can use other ports like `4001` or `4002` that are still free
